behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      # curiosity:
      #   gamma: 0.99
      #   strength: 0.1
      #   encoding_size: 256
      #   learning_rate: 0.0003
      #   network_settings:
      #     vis_encode_type: resnet
    keep_checkpoints: 5
    max_steps: 10800000 # 12 arenas a 3 agents a 3000 steps = 108000 * 100
    time_horizon: 128
    summary_freq: 108000 # 12 arenas a 3 agents a 3000 steps = 108000
    threaded: true

engine_settings:
  no_graphics: true

env_settings:
  env_path: /builds/AerialWildfireSuppression_hivex_windows
  num_envs: 12
  # training: 5000, inference: 6000
  seed: 5000

environment_parameters:
  # 0 false, 1 true
  training: 1
  # agent_count: 5
  # Communication: 0 No_Communication, 1 Broadcasting
  communication: [0, 1]
  # neighbour_count: 3
  # difficulty: 1
  reward_scale: 1

  human_intervention: 0
  time_scale: 20
  agent_count: 3
  ext_fire_reward: 200
  prep_tree_reward: 1
  water_pickup_reward: 1
  fire_out_reward: 0
  crash_reward: -100
  fire_close_to_city_reward: -100
  difficulty: 1
# mlagents-learn D:\dev\hivex_project\hivex_training\configs\mlagents\train\WildfireSup_hivex.yaml --env="D:\dev\hivex_project\hi_marl\env\Multi-Agent-Aerial-Wildfire-Suppression" --run-id="WFS_test_27" --no-graphics
