behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 10800000 # 12 arenas a 9 towers a 500 steps = 54000 * 200
    time_horizon: 128
    summary_freq: 54000 # 12 arenas a 9 towers a 500 steps = 54000
    threaded: true

engine_settings:
  no_graphics: true

env_settings:
  env_path: /builds/Wildfire_hivex_windows
  num_envs: 12
  # training: 5000, inference: 6000
  seed: 5000

environment_parameters:
  # 0 false, 1 true
  training: 1
  arena_count: 1
  # Communication: 0 No_Communication, 1 Broadcasting
  communication: [0, 1]
  # Difficulty range: [1-10]
  difficulty: 1
