name: "WildfireResourceManagement_V0"
tag: "WildfireResourceManagement"
policy: "PPO" # "IMPALA"
file_name: "hivex-environments/Hivex_WildfireResourceManagement_win/Hivex_WildfireResourceManagement.exe"
episode_horizon: 500
env_parameters:
  training: 1
  difficulty: 1
  task: 0
no_graphics: True
