name: "WindFarmControl_V0"
tag: "WindFarmControl"
policy: "PPO" # "IMPALA"
file_name: "hivex-environments/Hivex_WindFarmControl_win/Hivex_WindfarmControl.exe"
episode_horizon: 5000
env_parameters:
  training: 1
  pattern: 1
  task: 0
no_graphics: True
